services:
  - type: web
    name: sysml-to-arduino
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import db, app; db.create_all(app=app)"
    startCommand: gunicorn --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free