services:
  - type: web
    name: sysml-to-arduino
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free